using System.Text.Json.Serialization;

namespace CareNota.DTOs.Summary;


// ── GET /api/visits/{id}/summary ─────────────────────────────────────────────
// Returned to the doctor for review.
// IsApproved = false → draft (SOAP not yet written to Visit)
// IsApproved = true  → already approved (Visit.Subjective is populated)

public class VisitSummaryResponseDto
{
    public int VisitId { get; set; }
    public bool IsApproved { get; set; }

    // Doctor edits these SOAP fields before approving
    public DoctorSummaryDto DoctorSummary { get; set; } = new();

    // Patient-facing section — doctor can edit WhenToSeekHelp
    // FollowUpDate is set by the doctor during approval, not generated by AI
    public PatientSummaryDto PatientSummary { get; set; } = new();
}

public class DoctorSummaryDto
{
    public int AISummaryId { get; set; }
    public string Subjective { get; set; } = string.Empty;
    public string Objective { get; set; } = string.Empty;
    public string Assessment { get; set; } = string.Empty;
    public string Plan { get; set; } = string.Empty;
}

public class PatientSummaryDto
{
    public int AISummaryId { get; set; }
    public string Diagnosis { get; set; } = string.Empty;
    public string Symptoms { get; set; } = string.Empty;
    public string TreatmentPlan { get; set; } = string.Empty;

    // Doctor reviews and can edit this before approving
    public string WhenToSeekHelp { get; set; } = string.Empty;
}