using System.Text.Json.Serialization;

namespace CareNota.DTOs.Summary;

// ── Maps the exact JSON returned by POST /process-audio on FastAPI ────────────
public class AIProcessResponseDto
{
    [JsonPropertyName("doctor_summary")]
    public DoctorSummaryAIDto? DoctorSummary { get; set; }

    [JsonPropertyName("patient_summary")]
    public PatientSummaryAIDto? PatientSummary { get; set; }

    [JsonPropertyName("error")]
    public string? Error { get; set; }
}

// ── Doctor-side AI fields ────────────────────────────────────────────────────
public class DoctorSummaryAIDto
{
    [JsonPropertyName("subjective")]
    public string Subjective { get; set; } = string.Empty;

    [JsonPropertyName("objective")]
    public string Objective { get; set; } = string.Empty;

    [JsonPropertyName("assessment")]
    public string Assessment { get; set; } = string.Empty;

    [JsonPropertyName("plan")]
    public string Plan { get; set; } = string.Empty;
}

// ── Patient-side AI fields (Arabic) ──────────────────────────────────────────
public class PatientSummaryAIDto
{
    [JsonPropertyName("diagnosis")]
    public string Diagnosis { get; set; } = string.Empty;

    [JsonPropertyName("symptoms")]
    public string Symptoms { get; set; } = string.Empty;

    [JsonPropertyName("treatment_plan")]
    public string TreatmentPlan { get; set; } = string.Empty;

    [JsonPropertyName("when_to_seek_help")]
    public string WhenToSeekHelp { get; set; } = string.Empty;

    [JsonPropertyName("follow_up")]
    public string FollowUp { get; set; } = string.Empty;
}

// ── GET /api/visits/{id}/summary ─────────────────────────────────────────────
// Returned to the doctor for review before approval.
// IsApproved = false → draft  |  IsApproved = true → already approved
public class VisitSummaryResponseDto
{
    public int VisitId { get; set; }
    public bool IsApproved { get; set; }
    public DoctorSummaryDto DoctorSummary { get; set; } = new();
    public PatientSummaryDto PatientSummary { get; set; } = new();
}

public class DoctorSummaryDto
{
    public int AISummaryId { get; set; }
    public string Subjective { get; set; } = string.Empty;
    public string Objective { get; set; } = string.Empty;
    public string Assessment { get; set; } = string.Empty;
    public string Plan { get; set; } = string.Empty;
}

public class PatientSummaryDto
{
    public int AISummaryId { get; set; }
    public string Diagnosis { get; set; } = string.Empty;
    public string Symptoms { get; set; } = string.Empty;
    public string TreatmentPlan { get; set; } = string.Empty;
    // Doctor can edit this before approving
    public string WhenToSeekHelp { get; set; } = string.Empty;
    public string FollowUp { get; set; } = string.Empty;
}

// ── PUT /api/visits/{id}/summary ─────────────────────────────────────────────
// Null fields are preserved — only send what changed.
public class EditSummaryDto
{
    // SOAP fields (doctor side)
    public string? Subjective { get; set; }
    public string? Objective { get; set; }
    public string? Assessment { get; set; }
    public string? Plan { get; set; }

    // Patient Arabic fields — doctor can refine
    public string? Diagnosis { get; set; }
    public string? Symptoms { get; set; }
    public string? TreatmentPlan { get; set; }
    public string? WhenToSeekHelp { get; set; }
    public string? FollowUp { get; set; }
}

// ── POST /api/visits/{id}/summary/approve ────────────────────────────────────
// FollowUpDate is set by the doctor — not generated by the AI.


// ── GET /api/visits/{id}/patient-summary ─────────────────────────────────────
// Returned to the patient ONLY after the doctor has approved.
public class PatientSummaryViewDto
{
    public int VisitId { get; set; }
    public DateTime VisitDate { get; set; }

    // From Visit (written on approval)
    public string Diagnosis { get; set; } = string.Empty;   // from Diagnoses table
    public string Symptoms { get; set; } = string.Empty;    // Visit.Symptoms
    public string TreatmentPlan { get; set; } = string.Empty; // Prescription.Instructions
    public string WhenToSeekHelp { get; set; } = string.Empty; // Visit.WhenToSeekHelp
    public string FollowUp { get; set; } = string.Empty;
}


// ── POST /api/visits/{id}/summary/rating ─────────────────────────────────────
public class RateSummaryDto
{
    public int Rating { get; set; }       // 1–5
    public string? Feedback { get; set; } // Optional free text
}

public class RateSummaryResponseDto
{
    public int AISummaryID { get; set; }
    public int Rating { get; set; }
    public string? Feedback { get; set; }
    public string Message { get; set; } = string.Empty;
}