
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
namespace CareNota.DTOs.Summary;



// ── Maps the exact JSON returned by POST /process-audio on FastAPI ───────────


public class AIProcessResponseDto
{
    [JsonPropertyName("doctor_summary")]
    public DoctorSummaryAIDto? DoctorSummary { get; set; }

    [JsonPropertyName("patient_summary")]
    public PatientSummaryAIDto? PatientSummary { get; set; }

    [JsonPropertyName("error")]
    public string? Error { get; set; }
}

public class DoctorSummaryAIDto
{
    [JsonPropertyName("subjective")]
    public string Subjective { get; set; } = string.Empty;

    [JsonPropertyName("objective")]
    public string Objective { get; set; } = string.Empty;

    [JsonPropertyName("assessment")]
    public string Assessment { get; set; } = string.Empty;

    [JsonPropertyName("plan")]
    public string Plan { get; set; } = string.Empty;
}

public class PatientSummaryAIDto
{
    [JsonPropertyName("diagnosis")]
    public string Diagnosis { get; set; } = string.Empty;

    [JsonPropertyName("symptoms")]
    public string Symptoms { get; set; } = string.Empty;

    [JsonPropertyName("treatment_plan")]
    public string TreatmentPlan { get; set; } = string.Empty;

    [JsonPropertyName("when_to_seek_help")]
    public string WhenToSeekHelp { get; set; } = string.Empty;

    [JsonPropertyName("follow_up")]
    public string FollowUp { get; set; } = string.Empty;
}

// ── PUT /api/visits/{id}/summary ─────────────────────────────────────────────
// Doctor edits the draft before approving.
// Every field is nullable — only send what changed, null = keep as-is.

public class EditSummaryDto
{
    // SOAP fields (doctor side)
    public string? Subjective { get; set; }
    public string? Objective { get; set; }
    public string? Assessment { get; set; }
    public string? Plan { get; set; }

    // Patient side — doctor can refine the AI-generated text
    public string? WhenToSeekHelp { get; set; }
}
// ── POST /api/visits/{id}/summary/approve ────────────────────────────────────
// Doctor finalises the summary.
// FollowUpDate is set by the doctor — it is not generated by the AI.

public class ApproveSummaryDto
{
    // Optional: doctor sets the patient's next appointment date
    public DateTime? FollowUpDate { get; set; }
}
// ── GET /api/visits/{id}/patient-summary ─────────────────────────────────────
// Returned to the patient ONLY after the doctor has approved.
// All fields are in Arabic (as generated by FastAPI and edited by the doctor).

public class PatientSummaryViewDto
{
    public int VisitId { get; set; }
    public DateTime VisitDate { get; set; }

    // From AISummary (SummaryType = "Patient")
    public string Diagnosis { get; set; } = string.Empty;
    public string Symptoms { get; set; } = string.Empty;
    public string TreatmentPlan { get; set; } = string.Empty;

    // From Visit (written on approval)
    public string WhenToSeekHelp { get; set; } = string.Empty;
    public DateTime? FollowUpDate { get; set; }
}
